SacramentMeetingPlanner/Models/ErrorViewModel.cs
namespace SacramentMeetingPlanner.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SacramentMeetingPlanner/Models/SacramentMeeting.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SacramentMeetingPlanner.Models
{
    public class SacramentMeeting
    {
        public int Id { get; set; }

        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        
        [Display(Name = "Conducting Leader")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$")]
        [StringLength(30)]
        public string ConductingLeaderName { get; set; }
        
        [Display(Name = "Opening Hymn")]
        [Range(1,341)]
        public int OpeningHymn { get; set; }
        
        [Display(Name = "Sacrament Hymn")]
        [Range(1, 341)]
        public int SacramentHymn { get; set; }
        
        [Display(Name = "Intermediate Hymn Or Musical Number")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$")]
        [StringLength(30)]
        public string? IntermediateHymnOrMusicalNumber { get; set; }

        [Display(Name = "Closing Hymn")]
        [Range(1, 341)]
        public int ClosingHymn { get; set; }

        [Display(Name = "Opening Prayer")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$")]
        [StringLength(30)]
        public string OpeningPrayerPerson { get; set; }
        
        [Display(Name = "Closing Prayer")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$")]
        [StringLength(30)]
        public string ClosingPrayerPerson { get; set; }

        [Display(Name = "Number Of Speakers")]
        [Range(0, int.MaxValue, ErrorMessage ="Number of Speakers must be greater or equal to zero")]
        public int NumberOfSpeakers { get; set; }

        [Display(Name = "Talk Subjects")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$")]
        [StringLength(100)]
        public string SpeakerSubjects { get; set; }
    }
}

SacramentMeetingPlanner/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SacramentMeetingPlanner.Models;
using System.Diagnostics;

namespace SacramentMeetingPlanner.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SacramentMeetingPlanner/Controllers/SacramentMeetingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SacramentMeetingPlanner.Data;
using SacramentMeetingPlanner.Models;

namespace SacramentMeetingPlanner.Controllers
{
    public class SacramentMeetingsController : Controller
    {
        private readonly SacramentMeetingPlannerContext _context;

        public SacramentMeetingsController(SacramentMeetingPlannerContext context)
        {
            _context = context;
        }

        // GET: SacramentMeetings
        public async Task<IActionResult> Index()
        {
              return _context.SacramentMeeting != null ? 
                          View(await _context.SacramentMeeting.ToListAsync()) :
                          Problem("Entity set 'SacramentMeetingPlannerContext.SacramentMeeting'  is null.");
        }

        // GET: SacramentMeetings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.SacramentMeeting == null)
            {
                return NotFound();
            }

            var sacramentMeeting = await _context.SacramentMeeting
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sacramentMeeting == null)
            {
                return NotFound();
            }

            return View(sacramentMeeting);
        }

        // GET: SacramentMeetings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SacramentMeetings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date,ConductingLeaderName,OpeningHymn,SacramentHymn,IntermediateHymnOrMusicalNumber,ClosingHymn,OpeningPrayerPerson,ClosingPrayerPerson, NumberOfSpeakers, SpeakerSubjects")] SacramentMeeting sacramentMeeting)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sacramentMeeting);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sacramentMeeting);
        }

        // GET: SacramentMeetings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.SacramentMeeting == null)
            {
                return NotFound();
            }

            var sacramentMeeting = await _context.SacramentMeeting.FindAsync(id);
            if (sacramentMeeting == null)
            {
                return NotFound();
            }
            return View(sacramentMeeting);
        }

        // POST: SacramentMeetings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,ConductingLeaderName,OpeningHymn,SacramentHymn,IntermediateHymnOrMusicalNumber,ClosingHymn,OpeningPrayerPerson,ClosingPrayerPerson, NumberOfSpeakers, SpeakerSubjects")] SacramentMeeting sacramentMeeting)
        {
            if (id != sacramentMeeting.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sacramentMeeting);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SacramentMeetingExists(sacramentMeeting.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sacramentMeeting);
        }

        // GET: SacramentMeetings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.SacramentMeeting == null)
            {
                return NotFound();
            }

            var sacramentMeeting = await _context.SacramentMeeting
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sacramentMeeting == null)
            {
                return NotFound();
            }

            return View(sacramentMeeting);
        }

        // POST: SacramentMeetings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.SacramentMeeting == null)
            {
                return Problem("Entity set 'SacramentMeetingPlannerContext.SacramentMeeting'  is null.");
            }
            var sacramentMeeting = await _context.SacramentMeeting.FindAsync(id);
            if (sacramentMeeting != null)
            {
                _context.SacramentMeeting.Remove(sacramentMeeting);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SacramentMeetingExists(int id)
        {
          return (_context.SacramentMeeting?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SacramentMeetingPlanner/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div>
    <!-- <h1 class="display-4">Welcome</h1> -->
    <!-- https://newsroom.churchofjesuschrist.org/media/orig/Blessing_the_sacrament.jpg
        https://newsroom.churchofjesuschrist.org/media/960x540/Sacrament_Meeting.jpg
        https://www.churchofjesuschrist.org/bc/content/ldsorg/church/news/09/06/580-speaking-in-church.jpg
        https://assets.churchofjesuschrist.org/d1/2b/d12bb85e50003f926d788b2b6dabb8e3e96ef14d/d12bb85e50003f926d788b2b6dabb8e3e96ef14d.jpeg
    -->
    <!-- Slideshow container -->
    <div class="slideshow-container">

        <!-- Full-width images with number and caption text -->
        <div class="mySlides slide-fade">
            <div class="numbertext">1 / 4</div>
            <img src="https://newsroom.churchofjesuschrist.org/media/orig/Blessing_the_sacrament.jpg" style="width:100%">
            <div class="text"> </div>
        </div>

        <div class="mySlides slide-fade">
            <div class="numbertext">2 / 4</div>
            <img src="https://newsroom.churchofjesuschrist.org/media/960x540/Sacrament_Meeting.jpg" style="width:100%">
            <div class="text"> </div>
        </div>

        <div class="mySlides slide-fade">
            <div class="numbertext">3 / 4</div>
            <img src="https://www.churchofjesuschrist.org/bc/content/ldsorg/church/news/09/06/580-speaking-in-church.jpg" style="width:100%">
            <div class="text"> </div>
        </div>

        <div class="mySlides slide-fade">
            <div class="numbertext">4 / 4</div>
            <img src="https://assets.churchofjesuschrist.org/d1/2b/d12bb85e50003f926d788b2b6dabb8e3e96ef14d/d12bb85e50003f926d788b2b6dabb8e3e96ef14d.jpeg" style="width:100%">
            <div class="text"> </div>
        </div>

        <!-- Next and previous buttons -->
        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>
    </div>
    <br>
    <!-- The dots/circles -->
    <div style="text-align:center">
        <span class="dot" onclick="currentSlide(1)"></span>
        <span class="dot" onclick="currentSlide(2)"></span>
        <span class="dot" onclick="currentSlide(3)"></span>
        <span class="dot" onclick="currentSlide(4)"></span>
    </div>


    <hr />

    <div>
    <p>Sacrament meeting is the most important meeting of the week, the one the Lord has commanded us to attend. It’s a time to worship the Savior. - Elder W. Mack Lawrence April 1991</p>

        <a asp-area="" asp-controller="Home" asp-action="Index">
            Plan Sacrament Meeting
        </a>
    </div>

</div>



<script>
    let slideIndex = 1;
showSlides(slideIndex);

// Next/previous controls
function plusSlides(n) {
  showSlides(slideIndex += n);
}

// Thumbnail image controls
function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
} 
</script>

SacramentMeetingPlanner/Views/SacramentMeetings/Create.cshtml
@model SacramentMeetingPlanner.Models.SacramentMeeting

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Sacrament Meeting</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConductingLeaderName" class="control-label"></label>
                <input asp-for="ConductingLeaderName" class="form-control" />
                <span asp-validation-for="ConductingLeaderName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpeningHymn" class="control-label"></label>
                <input asp-for="OpeningHymn" class="form-control" />
                <span asp-validation-for="OpeningHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SacramentHymn" class="control-label"></label>
                <input asp-for="SacramentHymn" class="form-control" />
                <span asp-validation-for="SacramentHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IntermediateHymnOrMusicalNumber" class="control-label"></label>
                <input asp-for="IntermediateHymnOrMusicalNumber" class="form-control" />
                <span asp-validation-for="IntermediateHymnOrMusicalNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClosingHymn" class="control-label"></label>
                <input asp-for="ClosingHymn" class="form-control" />
                <span asp-validation-for="ClosingHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpeningPrayerPerson" class="control-label"></label>
                <input asp-for="OpeningPrayerPerson" class="form-control" />
                <span asp-validation-for="OpeningPrayerPerson" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClosingPrayerPerson" class="control-label"></label>
                <input asp-for="ClosingPrayerPerson" class="form-control" />
                <span asp-validation-for="ClosingPrayerPerson" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfSpeakers" class="control-label"></label>
                <input asp-for="NumberOfSpeakers" class="form-control" />
                <span asp-validation-for="NumberOfSpeakers" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpeakerSubjects" class="control-label"></label>
                <input asp-for="SpeakerSubjects" class="form-control" />
                <span asp-validation-for="SpeakerSubjects" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SacramentMeetingPlanner/Views/SacramentMeetings/Delete.cshtml
@model SacramentMeetingPlanner.Models.SacramentMeeting

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sacrament Meeting</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConductingLeaderName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConductingLeaderName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OpeningHymn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OpeningHymn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SacramentHymn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SacramentHymn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IntermediateHymnOrMusicalNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IntermediateHymnOrMusicalNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClosingHymn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClosingHymn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OpeningPrayerPerson)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OpeningPrayerPerson)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClosingPrayerPerson)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClosingPrayerPerson)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfSpeakers)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberOfSpeakers)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SpeakerSubjects)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SpeakerSubjects)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SacramentMeetingPlanner/Views/SacramentMeetings/Details.cshtml
@model SacramentMeetingPlanner.Models.SacramentMeeting

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Sacrament Meeting</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConductingLeaderName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConductingLeaderName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OpeningHymn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OpeningHymn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SacramentHymn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SacramentHymn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IntermediateHymnOrMusicalNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IntermediateHymnOrMusicalNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClosingHymn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClosingHymn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OpeningPrayerPerson)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OpeningPrayerPerson)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClosingPrayerPerson)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClosingPrayerPerson)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfSpeakers)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberOfSpeakers)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SpeakerSubjects)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SpeakerSubjects)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SacramentMeetingPlanner/Views/SacramentMeetings/Edit.cshtml
@model SacramentMeetingPlanner.Models.SacramentMeeting

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Sacrament Meeting</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConductingLeaderName" class="control-label"></label>
                <input asp-for="ConductingLeaderName" class="form-control" />
                <span asp-validation-for="ConductingLeaderName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpeningHymn" class="control-label"></label>
                <input asp-for="OpeningHymn" class="form-control" />
                <span asp-validation-for="OpeningHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SacramentHymn" class="control-label"></label>
                <input asp-for="SacramentHymn" class="form-control" />
                <span asp-validation-for="SacramentHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IntermediateHymnOrMusicalNumber" class="control-label"></label>
                <input asp-for="IntermediateHymnOrMusicalNumber" class="form-control" />
                <span asp-validation-for="IntermediateHymnOrMusicalNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClosingHymn" class="control-label"></label>
                <input asp-for="ClosingHymn" class="form-control" />
                <span asp-validation-for="ClosingHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpeningPrayerPerson" class="control-label"></label>
                <input asp-for="OpeningPrayerPerson" class="form-control" />
                <span asp-validation-for="OpeningPrayerPerson" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClosingPrayerPerson" class="control-label"></label>
                <input asp-for="ClosingPrayerPerson" class="form-control" />
                <span asp-validation-for="ClosingPrayerPerson" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfSpeakers" class="control-label"></label>
                <input asp-for="NumberOfSpeakers" class="form-control" />
                <span asp-validation-for="NumberOfSpeakers" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpeakerSubjects" class="control-label"></label>
                <input asp-for="SpeakerSubjects" class="form-control" />
                <span asp-validation-for="SpeakerSubjects" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SacramentMeetingPlanner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sacrament Meeting Planner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SacramentMeetingPlanner.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sacrament Meeting Planner</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SacramentMeetings" asp-action="Index">Meeting Planner</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Sacrament Meeting Planner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>